name: Build Desktop App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

      - name: Check for changes
        id: check-changes
        run: |
          # Use turbo-ignore to check if we need to build
          if npx turbo-ignore @draftking/desktop; then
            echo "should_build=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          else
            echo "should_build=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
          fi

      - name: Cache Turborepo Local Cache Directory
        if: steps.check-changes.outputs.should_build == 'true'
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install Wine
        if: steps.check-changes.outputs.should_build == 'true'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine64 wine32:i386

      - name: Build Desktop App
        if: steps.check-changes.outputs.should_build == 'true'
        run: yarn turbo run build --filter=@draftking/desktop...
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

      - name: Upload Windows artifact
        if: steps.check-changes.outputs.should_build == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: |
            apps/desktop/dist/*.exe
            apps/desktop/dist/*.blockmap
          compression-level: 9